[package]

name = "unjson"
version = "0.0.3"
authors = ["Dave Herman <dherman@mozilla.com>"]
license = "MIT"
description = "Tools for destructuring JSON data."
repository = "https://github.com/dherman/esprit"

[dependencies]
serde_json = "0.7.1"
